version: '3'
services:
  caddy:
    image: abiosoft/caddy:0.11.2-no-stats
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./.caddy:/root/.caddy
    depends_on:
      - web
